### ISSUE TITLE
PR 343 introduce FTBFS

### ISSUE THREAD

**Issue by agaida** [lxqt/libfm-qt#345]
#### Expected Behavior

Should not fail to build

##### Current Behavior

Fails to build - @PCMan mentioned a switch for Qt 5.12

```
/build/libfm-qt-0.14.0~326-g94db29d/src/filedialog.cpp: In member function ‘void Fm::FileDialog::FileDialogFilter::update()’:
/build/libfm-qt-0.14.0~326-g94db29d/src/filedialog.cpp:973:75: error: ‘wildcardToRegularExpression’ is not a member of ‘QRegularExpression’
                                                     + QRegularExpression::wildcardToRegularExpression(glob)
                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [src/CMakeFiles/fm-qt.dir/build.make:1184: src/CMakeFiles/fm-qt.dir/filedialog.cpp.o] Error 1
```

##### Possible Solution
just fix it :) 

* Qt Version: 5.11.3+dfsg-2

**Comment by tsujan** [comment]
Wow! I didn't know that `QRegularExpression::wildcardToRegularExpression()` was from 5.12 and misunderstood @PCMan's comment!! Will correct it as soon as possible.

**Comment by agaida** [comment]
Cool, thanks :)

**Comment by tsujan** [comment]
Done. Please test!

This was a good example as to why making 2 changes in one PR is wrong; will never do it again.

**Comment by agaida** [comment]
Done, compile.

**Comment by tsujan** [comment]
> pcmanfm-qt build against too - so, i will merge it

Yes, because it's the same old code for Qt5 < 5.12 (except for the mime type fix).

I wanted to hunt every occurrence of `QRegExp` methods in libfm-qt/pcmanfm-qt and replace it with a `QRegularExpression` method but, apparently, either it's too soon or I should pay more attention to Qt versions.

`QRegularExpression` is more powerful than `QRegExp` (although its power isn't used by libfm-qt). Moreover, `QRegExp` is like `QDesktopWidget`: sooner or later, it won't work correctly.
