### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by jubalh** [lxqt/libfm-qt#370]
Seems like two files are GPL-2.0+ licensed:
* src/core/vfs/vfs-menu.c
* src/core/vfs/vfs-search.c

while the rest is  LGPL-2.1-or-later. Is this intentional?

**Comment by tsujan** [comment]
> Is this intentional?

I'm not good at these nuances but I don't think there's a problem here.

@agaida ?

**Comment by agaida** [comment]
```
 *      fm-vfs-menu.c
 *      VFS for "menu://applications/" path using menu-cache library.
 *
 *      Copyright 2012-2014 Andriy Grytsenko (LStranger) <andrej@rep.kiev.ua>
 *
 *      This program is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation; either version 2 of the License, or
 *      (at your option) any later version.

 * fm-vfs-search.c
 * 
 * Copyright 2012 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
 * Copyright 2010 Shae Smittle <starfall87@gmail.com>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
``` 

So i would say, yes, intentional, 'old' code from LXDE. I have no problem with - i have a problem with the description :sunglasses: 

```
 *      fm-vfs-menu.c
 *      VFS for "menu://applications/" path using menu-cache library.
```

**Comment by agaida** [comment]
more verbose - as long it is used in pcmanfm-qt i see no problems, but if one try to link this against non-free ...

**Comment by tsujan** [comment]
"vfs-search.c" is changed by me recently -- if that has any relevance at all.

**Comment by agaida** [comment]
not really - you provide your code based on the license the file is under - or a compatible one - in that case you had to mark your changes and mention the license. But that don't change anything what the original author has chosen.

**Comment by agaida** [comment]
like in: https://github.com/lxqt/libfm-qt/commit/f0f38ace39438dee4f3fc8f6948cd93020a52b85

**Comment by damianatorrpm** [comment]
lucky that I have read this, not just before the pre-release legal review

for the time being I have created a fork:
https://github.com/damianatorrpm/libfm-qt-lgpl

**Comment by damianatorrpm** [comment]
May I ask additionally if you have asked the 3 people I see mentioned in the headers?
If not I would ask via e-mail to have clarity.

**Comment by agaida** [comment]
maybe i'm dumb - but why are these files important? See my point of view above.

**Comment by damianatorrpm** [comment]
@PCMan @tsujan @jubalh 

@agaida
 You are not developing a closed application that will link to libfm-qt (or the LGPL fork). I am.


> maybe i'm dumb - but why these files are important? See my point of view above. If the license of both files hinder us to do things we want to - we will take care of. Right now i see no need for any action tbh.

I am not certain that I have understood your point of view, you have a LGPL library (at least you state that it is, which would require all of it's files to be LGPL). In case I understand your POV you just don't care about deliberately being misleading about that. If I did understand it correctly, I see myself only doing the following:
1) Ceasing any kind of contribution to projects in the lxqt namespace. 
2) Maintaining the (really LGPL) free fork or create a closed replacement instead.
3) Filing reports in all major commercial bug trackers (redhat, suse) for removal 
     of libfm-qt because of it's licence status. (RPM packages having correct licence marked is pretty important for them)

**Comment by tsujan** [comment]
> Filing reports in all major commercial bug trackers (redhat, suse) for removal of libfm-qt because of it's licence status.

Sorry to interrupt -- I won't participate in this discussion -- but such claims have always sounded like bad jokes to me.

> Ceasing any kind of contribution to projects in the lxqt namespace.

It's up to the developer. No one is forced to do anything here and no one expects anything only because of his contribution.

**Comment by PCMan-Appier** [comment]
These are wrong and need to be fixed.
Long time ago we relicensed libfm from gpl2 to lgpl2 and updated the headers of all files.
I think these two were accidentally omitted.

**Comment by PCMan** [comment]
Opps I forgot to switch my account. Lol

**Comment by novoslinux** [comment]
> These are wrong and need to be fixed.
Glad to hear you see it that way!

```
vfs-search.c
 * Copyright 2012 Hong Jen Yee (PCMan) <pcman.tw@gmail.com>
 * Copyright 2010 Shae Smittle <starfall87@gmail.com>
```

```
 *      fm-vfs-menu.c
 *      Copyright 2012-2014 Andriy Grytsenko (LStranger) <andrej@rep.kiev.ua>
```

It should be sufficient for them to drop a note here that they consent with this (github account should be linked to the email address there) and changing the header of those files.

**Comment by agaida** [comment]
@PCMan - nice that you take care of.

@damianatorrpm - ok, the first and also the last time i will talk about it. I could understand your words as a kind of blackmailing. So, please don't do such things again. otherwise i guess we should not work together.

**Comment by damianatorrpm** [comment]
@agaida 

> I could understand your words as a kind of blackmailing. 

This was not the intention and I regret if it came along like that.
Having a relationship with open source means to rely on the "community" contract,
which in my eyes means if I download libfm-qt-devel from redhat which has it marked as LGPL in the rpm header, go to the upstream repo see LGPL I expect it to be usable as LGPL. (else what? I link to fm-qt in closed source application - it's not released yet - and you sue me because of these two headers?). I am sure that no-one would want to be in the position asking the same questions.

**Comment by agaida** [comment]
:) - it is highly unlikely that one will be sued over these two files - there are much steps are needed to sue somebody because of GPL violations. Second - the sources are LGPL mainly, except the mentioned files (GPL 2+) and the cmake file which is BSD-3-clause. You are right that both things should be mentioned in the README, for the GPL files it is not imho not needed anymore, couldn't do it retro-active.

For our use case  both files are not that important - it is not relevant if the resulting binary is GPLed or not, because all applications that are linked against libfm-qt are licensed as GPL 2+, please see also the historical context. For uses outside of LXQt things are different. 

For now the solution is to mention these three files explicitly - the mention of GPL can be removed when the licences of both files are changed or the files are removed.

**Comment by agaida** [comment]
@PCMan - Please remove the mention of GPL in README.md and the GPL root license file if solved.

**Comment by PCMan** [comment]
![圖片](https://user-images.githubusercontent.com/46543/56379151-a14bb380-6241-11e9-8003-b5d2351c5c07.png)
Found this in my mail box. I think the code we got from libfm should be LGPL2.

**Comment by PCMan** [comment]
Fixed in this PR: https://github.com/lxqt/libfm-qt/pull/405

**Comment by PCMan** [comment]
@jubalh @damianatorrpm Thank you for helping us clarify the license. It's a very important issue for any open source project. Basically Andriy and I are the main authors of libfm (where these pieces of code came from). Andriy help relicensed libfm to LGPL 2 several years ago and he is the author of these two files. So I corrected the file headers to reflect the LGPL2 license of libfm.

**Comment by PCMan** [comment]
@agaida @tsujan Thanks for bringing up the discussions and I'm glad that the problem can be solved. So nobody need to continue the argument. However, do you think that we can be more friendly to others in the community no matter we agree with them or not?

People all come here because they like and care about our project. Different opinions should be more welcomed so we can keep improving. Having disagreement is quite normal when different people are working together. Luckily most of them can be solved with enough communications.

Thanks!

**Comment by agaida** [comment]
@damianatorrpm - with my remark in the PR - you will need to use the libfm-qt with the changed license. And i should talk with our release team in debian how to handle ...
@jubalh - would you be so kind to ask your release team too how to handle such situations?

**Comment by tsujan** [comment]
@PCMan I know I have a bad temper sometimes but when I see a good work, I change it to its opposite.
That's not a good excuse, I know. And you're completely right.

**Comment by PCMan** [comment]
@agaida @tsujan Thank you.
I just merged the license update into master branch and described the exact date on which libfm changed the license to LGPL2 in the commit log. So if there are no other concerns I think we can close this issue.

**Comment by damianatorrpm** [comment]
@PCMan 
Thank you very much.

**Comment by agaida** [comment]
just uploaded to debian unstable, unblock request is here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927380

**Comment by agaida** [comment]
unblocked for debian - @tsimonq2 maybe this should be done for ubuntu too
