### ISSUE TITLE
allow using any terminal emulator specified by programs instead of only from a list file

### ISSUE THREAD

**Issue by SArpnt** [lxqt/libfm-qt#922]
for my particular case the issue is a bit of a mix between things in this library, pcmanfm-qt, and arguably lxqt-archiver
i decided to put the issue here since the list of terminals is part of this project, and i don't think the other projects are what force the list, but maybe i made a mistake while reading the code. i hope it isn't an issue.

currently if i try to use a terminal in pcmanfm-qt that isn't in the terminals.list, it defaults to xterm. this affects opening folders in a terminal using the right click shortcut and any desktop entries that use `Terminal=true`

##### Expected Behavior
what i expected originally is that any terminal emulator set in the $TERMINAL environment variable would work, but i've heard the lxqt team decided that was a bad idea (i don't know why). the next thing i expected would be that there's some way to configure a custom terminal, whether that's in individual programs such as pcmanfm-qt and lxqt-archiver, or with a config file or set of config files in locations such as `~/.config/libfm-qt/terminals.list`, `~/.config/libfm-qt/terminals.list.d`, `/etc/libfm-qt/terminals.list`

##### Current Behavior
currently only terminals from the terminals.list data file can be used to open programs, and there doesn't seem to be a user version of this file or a system like a conf.d directory. only the root user can add new entries and it's incompatible with package updates

##### Context
i use the foot terminal emulator, which isn't in the list. (i created a pr for it, but when that's done you can just pretend i'm using a new terminal emulator) i was trying to use pcmanfm-qt, which has a number of problems with the user interface:
![image](https://github.com/lxqt/libfm-qt/assets/36542932/e5d085a9-12a5-4c0a-aa33-5b4c90e62068)
the text input and example suggest that the terminal selector allows typing in any program with syntax to work with any terminal that might exist, and the only thing showing a dropdown is alllll the way to the right. this is in contrast to archiver integration which isn't a text input.

despite the text input, the only things that work are the options in the dropdown, and they don't use the syntax shown in the example.

ideally pcmanfm-qt would default to the $TERMINAL variable (or maybe not, but i wouldn't know why), and/or allow setting any properties of the terminal emulator, maybe with the current list used as presets, but not forced

**Comment by tsujan** [comment]
> ... a config file or set of config files in locations such as ~/.config/libfm-qt/terminals.list, ~/.config/libfm-qt/terminals.list.d, /etc/libfm-qt/terminals.list

A suboptimal design in libfm-qt → `terminal.cpp`. It can only read "LIBFM_QT_DATA_DIR/terminals.list", but that wouldn't be a problem if it could accept a terminal not found in the list.

> the text input and example suggest that the terminal selector allows typing in any program

I think the original author made it so for future, having a plan. That's my guess, because of which, I've changed neither that combo-box nor `terminal.cpp`. Perhaps it's time to do something about the latter (after the next release).

***

To prevent misunderstanding, I emphasize that what follows isn't about what you said or did. It's related to the topic though.

The fact is that *there's no standard way of setting the default terminal emulator.*

That's why file management libraries may use a list of known terminal emulators. GLib has an internal list which gives the priority to `gnome-terminal` → `konsole` → `xterm`. libfm-qt uses `xterm` as fallback and has an external list (mentioned above).

So, the problem you encountered with `lxqt-archiver` in https://github.com/lxqt/lxqt-archiver/issues/366 may also happen with other apps. Until a general solution is found, `xterm` is required.

**Comment by tsujan** [comment]
@SArpnt
If you use git, please test https://github.com/lxqt/libfm-qt/pull/924.

**Comment by tsujan** [comment]
Also, the current GUI of PCManFM-Qt's Preferences dialog is used for adding terminals  → https://github.com/lxqt/pcmanfm-qt/pull/1810
