### ISSUE TITLE
Renaming a file upon completion causes the previous file to be selected

### ISSUE THREAD

**Issue by isf63** [lxqt/libfm-qt#923]
I'm not sure of the term for when a file is "semi-selected", that is, selected but unable to be opened with Enter, but this "semi-selection" is what I'm referring to. It looks like this on the Fusion theme:
![img](https://github.com/lxqt/libfm-qt/assets/121320947/505ad223-8c39-4848-b0be-403652c79af1)

Renaming a file in any of the view modes - Icon, Thumbnail, Compact, List - causes the previous file to be selected upon pressing Enter. Does not happen on the desktop, however there is another quirk there where no file is selected. For both it only happens if the filename is actually changed.

##### Expected Behavior
The same file is selected in pcmanfm-qt windows and Desktop upon renaming.

##### Steps to Reproduce (for bugs)
a. Rename a file in any of the pcmanfm-qt window modes and press Enter or click off of it to complete the renaming.
b. Same but for Desktop; in this case no file is selected

##### Context
It's a good visual cue, plus while Enter may not work on "semi-selected" files, arrow keys do.

##### System Information
* Package version: 1.3.0

**Comment by tsujan** [comment]
This isn't a bug. Read the detailed explanation below.

***

It's called the "current item" in list views, and it isn't limited to Qt.

Different styles may distinguish the current item differently: Fusion does what you see; Kvantum may draw a dotted rectangle (it depends on the Kvantum theme); Breeze draws a line below it; etc.

The current item may be selected or not. If not, it'll be selected by pressing Space once. Deselection can usually be done by Ctrl+Space.

The previous item should become the current item on renaming because renaming=removing+creating. At the moment an item is removed, the list needs a current item, and the best choice is the existing item before it.

In PCManFM-Qt check *Preferences → Behavior → Select newly created files*, and see the difference.

**Comment by isf63** [comment]
Ok, I see the option for "Select newly created files" and enabling it provides equivalent behavior - only selected instead of the "current item". Good to know about Space selecting a current item.

That solves that, but I don't understand,

>At the moment an item is removed, the list needs a current item, and the best choice is the existing item before it.

If a file is renamed, then its new filename is known and it is tractable to verify it was renamed successfully. The best choice is to make that the current item, _especially_ when the renaming causes the file to jump to a new location based on sorting settings.

**Comment by tsujan** [comment]
> ... especially when the renaming causes the file to jump to a new location based on sorting settings.

A user either wants to work on the renamed item or not. The above-mentioned option is for the first case — and much more.

Not every user likes a scroll jump, let alone a jump without selection, and adding yet another option for it would be a confusing overkill.
